import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Image from "next/image";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="w-full bg-black py-4 sticky top-0 z-50 shadow-md flex justify-center items-center">
          <Image
            src="/images/logo.png"
            alt="Luxe Wear 16 Logo"
            width={60}
            height={60}
            className="object-contain"
            priority
          />
        </header>
        <div className="flex-grow">
          {children}
        </div>
      </body>
    </html>
  );
}
